version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.5
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - coveralls/upload:
          flag_name: Test 1
          verbose: true
workflows:
    build-and-test:
      jobs:
        - build-and-test